version: '3'
services: 
  meu-blog:
    image: wordpress:6.2.2
    container_name: wordpress
    restart: always
    env_file:
      - .env
    ports:
      - 80:80
    volumes:
      - wordpress:/var/www/html
    networks:
      - meu-blog
    depends_on:
      - db  
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - db:/var/lib/mysql
    networks:
      - meu-blog
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 8081:80
    depends_on:
      - db
    networks:
      - meu-blog    
networks:
  meu-blog:
    driver: bridge
volumes:
  wordpress:
  db: